batch_size: 48
d0_kernel: 3
d0_proba: 0.3
d1_kernel: 3
d1_proba: 0.3
d2_kernel: 1
d2_proba: 0.3
device: ''
epochs: 50
fliplr: 0.5
flipud: 0.5
gb_kernel: 3
hsv_h: 0.02
hsv_s: 0.2
hsv_v: 0.5
lr0: 0.05
lrf: 0.1
optimizer: SGD
weight_decay: 0.0001
