fixed_layers: [ -2 ]
width_multiple: 1.125
depth_multiple: 1
img_size: 608
drop_pos: [ 8, 11, 13 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 16, 3, 2 ] ],    # 0
    [ -1, 1, Conv, [ 16, 3 ] ],
    [ -1, 1, Conv, [ 32, 3 ] ],
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],

    [ -1, 5, CSP_OSA, [ 32, 0.75 ] ], # 4
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],

    [ -1, 5, CSP_OSA, [ 64, 0.75 ] ], # 6
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],
    [ -1, 1, DropBlock, [ 3, 0.3 ] ],

    [ -1, 5, CSP_OSA, [ 128, 0.75 ] ],  # 9
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],
    [ -1, 1, DropBlock, [ 3, 0.3 ] ],

    [ -1, 5, CSP_OSA, [ 128, 0.75 ] ],  # 12
    [ -1, 1, DropBlock, [ 1, 0.3 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 7, 1 ] ],
    [ -1, 1, Squeeze, [ ] ]
  ]
